14 done
AAErm/otusHW pull request #14
Opened 2024-08-04 09:26 UTC by AAErm

Продолжаю плодить ветки т.к. предыдущие дз застряли на проверке

2024-08-05 14:56 UTC, agneum requested changes
Спасибо за вариант решения, однако есть существенные замечания:
- не реализована работа с RabbitMQ
- не реализованы сервисы планировщика и рассыльщика
- пайплайн не пройден

Возвращаю задание на доработку и прошу при создании PR использовать шаблон

2024-08-05 19:35 UTC, AAErm commented
@agneum Артем, на самом деле работа с кроликом реализована посредством сторонней библиотеки "github.com/imega/mt". В ней очень удобно реализовано переподключение к кролю в случае отвала соединения и хендлер похож на http-ый. Мы с бывшим коллегой ее когда-то написали. Для реализации простой логики ее хватает с головой.

Но если хотите, давайте перепишу реализацию на библиотеке github.com/streadway/amqp.

2024-08-05 20:06 UTC, AAErm commented
@agneum  Теперь вижу. Планировщик и  сендер попал в другой мердж. Видимо задания частично перепутал. сейчас чекаут файлов сделаю.

2024-08-06 12:35 UTC, AAErm commented on hw12_13_14_15_calendar/Makefile
>  	go build -v -o $(BIN) -ldflags "$(LDFLAGS)" ./cmd/calendar
утащил нужные изменения в более поздний мердж. уже спулил эти изменения с ветки hw15

2024-08-07 05:30 UTC, merged