HW4 done
AAErm/otusHW pull request #4
Opened 2024-03-13 15:26 UTC by AAErm

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [x] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [x] Я запустил `go mod tidy`.
- [x] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [x] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-03-14 03:27 UTC, agneum requested changes
Спасибо за вариант решения.
Хорошая работа, однако есть критичные замечания.
Возвращаю на доработку

2024-03-14 03:27 UTC, agneum commented on hw04_lru_cache/cache.go
> +	v, ok := value.(int)
Почему допускаются только целочисленные значения? По условиям задачи нет ограничения на хранимые данные

2024-03-14 03:27 UTC, agneum commented on hw04_lru_cache/cache.go
> +	}
> Сложность всех операций должна быть O(1), т.е. не должно быть мест, где осуществляется полный обход списка.

[Реализация двусвязного списка](https://github.com/AAErm/otusHW/tree/hw04_lru_cache/hw04_lru_cache#1-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F-%D0%B4%D0%B2%D1%83%D1%81%D0%B2%D1%8F%D0%B7%D0%BD%D0%BE%D0%B3%D0%BE-%D1%81%D0%BF%D0%B8%D1%81%D0%BA%D0%B0)

2024-03-14 03:27 UTC, agneum commented on hw04_lru_cache/cache.go
> +	for key := range l.items {
Аналогично, не должно быть полного перебора всех элементов

2024-03-14 03:27 UTC, agneum commented on hw04_lru_cache/list.go
> +// func (l *list) PushFront(v interface{}) *ListItem {
Закомментированный код желательно удалять

2024-03-14 03:27 UTC, agneum commented on hw04_lru_cache/list.go
> +	mu     sync.RWMutex
Я бы убрал мьютекс. В дополнительном задании предлагается сделать кэш горутино-безопасным, не список. 
То есть предполагается, что пользователи кэша будут работать с методами `Set`, `Get`, `Clear`

2024-05-31 19:06 UTC, AAErm commented on hw04_lru_cache/cache.go
> +	v, ok := value.(int)
исправил

2024-05-31 19:07 UTC, AAErm commented on hw04_lru_cache/cache.go
> +	}
для решения данной задачи не нашел лучше способа, чем хранить в кэше структуру из ключа и значения.

2024-05-31 19:07 UTC, AAErm commented on hw04_lru_cache/cache.go
> +	for key := range l.items {
исправил

2024-05-31 19:07 UTC, AAErm commented on hw04_lru_cache/list.go
> +// func (l *list) PushFront(v interface{}) *ListItem {
+

2024-05-31 19:07 UTC, AAErm commented on hw04_lru_cache/list.go
> +	mu     sync.RWMutex
+

2024-06-01 09:53 UTC, agneum requested changes
Спасибо за правки.
Решение выглядит хорошо, только пайплайн не проходит из-за упавших тестов списка
Возвращаю задачу на доработку. 
5/10

2024-06-01 09:53 UTC, agneum commented on hw04_lru_cache/cache.go
> +	}
И с проверкой, и без проверки в результате будет паника, поэтому можно не проверять

2024-06-01 09:53 UTC, agneum commented on hw04_lru_cache/cache.go
> +		l.items[key].Value = &cacheItem{key, value}
Желательно явно указывать ключи, иначе при изменении структуры есть риск ошибки

2024-06-01 09:53 UTC, agneum commented on hw04_lru_cache/list_test.go
> +		wg.Add(numConcurrent)
Тест не проходит из-за отсутствия механизма защиты данных при конкурентном обращении

```
=== RUN   TestConcurrentList
=== RUN   TestConcurrentList/concurrency
    list_test.go:69: 
        	Error Trace:	list_test.go:69
        	Error:      	Not equal: 
        	            	expected: 10000
        	            	actual  : 9319
        	Test:       	TestConcurrentList/concurrency
--- FAIL: TestConcurrentList (0.00s)
    --- FAIL: TestConcurrentList/concurrency (0.00s)
```

Но такой механизм здесь и не особо нужен, т.к. работа с кэшем не предполагает прямое управление списком

2024-06-01 09:53 UTC, agneum commented on hw04_lru_cache/cache.go
> +	}
Хорошее решение

2024-06-02 13:46 UTC, agneum approved these changes
Спасибо за правки. Принято

2024-06-06 15:28 UTC, merged